name: CI

on:
  push:
    branches:
    - master
    - heroku-deployment/*

jobs:
  build_konnections:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'konnections' }}
      run: |
        cd ./kontent-sample-app-conference-net
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
